# sysinfo
NAME = "Sysinfo v0.1"
NAMEC = "Sysinfo C v0.1"

# reportingengine & receivingengine
JUSTJOINED_KEYWORD = "HELLO!"
INFO_START_KEYWORD = "INFO START"
INFO_STOP_KEYWORD = "INFO STOP"
INFO_SEPARATOR_KEYWORD = "INFO SEPARATOR"
STATS_START_KEYWORD = "STATS START"
STATS_STOP_KEYWORD = "STATS STOP"
STATS_SEPARATOR_KEYWORD = "STATS SEPARATOR"

#databaseengine
SAVE_AFTER_N_NEW_ENTRIES = 10